sudo: false

language: go

go:
  - 1.12.x
  - 1.11.x
  - 1.10.x
  - master

env:
 global:
  - GO111MODULE=on

cache:
 directories:
  - $HOME/.cache/go-build
  - $HOME/gopath/pkg/mod

git:
 depth: 1

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
