sudo: false

language: go

go:
  - 1.12.x
  - 1.11.x
  - 1.10.x
  - master

os:
  - linux
  - osx
  - windows

env:
 global:
  - GO111MODULE=on
 matrix:
  - TAGS=""
  - TAGS="-tags bounds"
  - TAGS="-tags noasm"
  - TAGS="-tags appengine"

cache:
 directories:
  - $HOME/.cache/go-build
  - $HOME/gopath/pkg/mod

git:
 depth: 1

matrix:
 fast_finish: true
 exclude:
  - os: osx
    go: 1.12.x
    env: TAGS="-tags bounds"
  - os: osx
    go: 1.12.x
    env: TAGS="-tags noasm"
  - os: osx
    go: 1.12.x
    env: TAGS="-tags appengine"

  - os: osx
    go: 1.11.x
  - os: osx
    go: 1.10.x
  - os: osx
    go: master

  - os: windows
    go: 1.12.x
    env: TAGS="-tags bounds"
  - os: windows
    go: 1.12.x
    env: TAGS="-tags noasm"
  - os: windows
    go: 1.12.x
    env: TAGS="-tags appengine"

  - os: windows
    go: 1.11.x
  - os: windows
    go: 1.10.x
  - os: windows
    go: master
 allow_failures:
  - go: master

before_install:
 # This garbage is necessary because on windows, Travis
 # helpfully sets core.autocrlf to true.
 #
 # The block here repeats the clone after having unset
 # core.autcrlf. There is no simple way to do this
 # conditionally on OS because windows will not allow
 # a file to be removed or moved while the file is open,
 # and we use constructed paths to scripts to get
 # conditional execution.
 #
 # Happy windowsing!
 - pushd ../../..
 - mv github.com/seanhagen/bradleyterry .
 - git config --global core.autocrlf false
 - git clone bradleyterry github.com/seanhagen/bradleyterry
 - popd
